stages:
  prepare_data:
    cmd: bash prepare_dsprites.sh
    deps:
    - prepare_dsprites.sh
    outs:
    - data/
  train:
    cmd: python3 -m vsa_codebook_decoder.train
    deps:
    - conf/config.yaml
    - vsa_codebook_decoder/model/
